#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#include "dict.h"

struct dict_item {
  // Each word is at most 100 bytes.
  char word[100];
  // The length of each word.
  size_t len;
};

struct dict_t {
  // The path to the underlying file
  char *path;
  // The file descriptor of the opened file. Set by dictionary_open_map.
  int fd;
  // How many items the mmaped file should store (this will determine the size).
  // There are ~500k words in /usr/share/dict/words.
  size_t num_items;
  // A pointer to the first item.
  struct dict_item *base;
};

// Construct a new dict_t struct.
// data_file is where to write the data,
// num_items is how many items this data file should store.
struct dict_t *dictionary_new(char *data_file, size_t num_items) {
  struct dict_t *dict_n = malloc(sizeof(struct dict_t));
  dict_n->path = data_file;
  // dict_n->fd = (malloc(sizeof(int));
  dict_n->fd = -1;
  dict_n->num_items = num_items;

  return dict_n;
}

// Computes the size of the underlying file based on the # of items and the size
// of a dict_item.
size_t dictionary_len(struct dict_t *dict) {
  return dict->num_items * sizeof(struct dict_item);
}

// This is a private helper function. It should:
// Open the underlying path (dict->path), ftruncate it to the appropriate length
// (dictionary_len), then mmap it.
int dictionary_open_map(struct dict_t *dict) {
  size_t len = dictionary_len(dict);
  // dict->fd = open(dict->path, O_CREAT | O_RDWR, S_IRWXU | S_IRWXG);
  dict->fd = open(dict->path, O_CREAT | O_RDWR, 0777);
  if (dict->fd == -1) {
    perror("open");
    return 0;
  }
  if (ftruncate(dict->fd, len) == -1) {
    perror("truncate");
    return 0;
  }
  dict->base = mmap(NULL, len, PROT_READ | PROT_WRITE, MAP_SHARED, dict->fd, 0);
  if (dict->base == MAP_FAILED) {
    perror("mmap");
    return 0;
  }
  msync(dict->base, dictionary_len(dict), MS_SYNC);
  return 1;
}

// The rest of the functions should be whatever is left from the header that
// hasn't been defined yet.
// Good luck!

// Allocates a new dictionary. Underlying dictionary is not initialized,
// use dictionary_generate to generate a new dictionary.
// struct dict_t* dictionary_new(char *data_file, size_t num_items);

// Read the file at input. For each line in input, create a new dictionary
// entry.
int dictionary_generate(struct dict_t *dict, char *input) {
  if (!dictionary_open_map(dict)) {
    return -1;
  }
  FILE *input_file = fopen(input, "r");
  if (!input_file) {
    perror("fopen");
    return -1;
  }
  char line[100];
  int index = 0;
  while (fgets(line, 100, input_file)) {
    printf("line length: %zd\n", strlen(line));
    strcpy(dict->base[index].word, line);
    dict->base[index].len = strlen(line) - 1;
    index++;
  }
  fclose(input_file);
  msync(dict->base, dictionary_len(dict), MS_SYNC);
  return 0;
}

// load a dictionary that was generated by calling generate.
int dictionary_load(struct dict_t *dict) { return dictionary_open_map(dict); }

// Unmaps the given dictionary.
// Free/destroy the underlying dict. Does NOT delete the database file.
void dictionary_close(struct dict_t *dict) {
  munmap(dict->base, dictionary_len(dict));
  free(dict);
}

// returns pointer to word if it exists, null otherwise
char *dictionary_exists(struct dict_t *dict, char *word) {
  for (int i = 0; i < dict->num_items; i++) {
    if (strcmp(word, dict->base[i].word)) {
      return word;
    }
  }
  return NULL;
}

//// Count of words with len > n
int dictionary_larger_than(struct dict_t *dict, size_t n) {
  int count = 0;
  int i = 0;
  while (strlen(dict->base[i].word) > 0) {
    if (dict->base[i].len > n) {
      count++;
    }
    i++;
  }
  return count;
}

int dictionary_smaller_than(struct dict_t *dict, size_t n) {
  int count = 0;
  int i = 0;
  while (strlen(dict->base[i].word) > 0) {
    if (dict->base[i].len < n) {
      count++;
    }
    i++;
  }
  return count;
}

int dictionary_equal_to(struct dict_t *dict, size_t n) {
  int count = 0;
  int i = 0;
  while (strlen(dict->base[i].word) > 0) {
    if (dict->base[i].len == n) {
      count++;
    }
    i++;
  }
  return count;
}
